#!/bin/bash
source common.sh

./setup-bpelg

docker run betsy-bpelg sh betsy bpel --use-installed-engine bpelg "$*"

params=`echo "$*" | tr ' =' '_'`
folder=results/betsy-bpel-bpelg-$params-`date +%s`
container=`docker ps -alq`

extractLogs "$container" "$folder"
open "$folder/test/reports/results.html"
