#!/bin/bash
source common.sh

./setup-camunda730

docker run betsy-camunda730 sh betsy bpmn --use-installed-engine camunda730 "$*"

params=`echo "$*" | tr ' =' '_'`
folder=results/betsy-bpel-camunda730-$params-`date +%s`
container=`docker ps -alq`

extractLogs "$container" "$folder"
open "$folder/test/reports/results.html"
