#!/bin/bash
source common.sh

./setup-camunda720

docker run betsy-camunda720 sh betsy bpmn --use-installed-engine camunda720 "$*"

params=`echo "$*" | tr ' =' '_'`
folder=results/betsy-bpel-camunda720-$params-`date +%s`
container=`docker ps -alq`

extractLogs "$container" "$folder"
open "$folder/test/reports/results.html"
