#!/bin/bash
source common.sh

./setup-active-bpel

docker run betsy-active-bpel sh betsy bpel --use-installed-engine active-bpel "$*"

params=`echo "$*" | tr ' =' '_'`
folder=results/betsy-bpel-active-bpel-$params-`date +%s`
container=`docker ps -alq`

extractLogs "$container" "$folder"
open "$folder/test/reports/results.html"
