#!/bin/bash
source common.sh

./setup-orchestra

docker run betsy-orchestra sh betsy bpel --use-installed-engine orchestra "$*"

params=`echo "$*" | tr ' =' '_'`
folder=results/betsy-bpel-orchestra-$params-`date +%s`
container=`docker ps -alq`

extractLogs "$container" "$folder"
open "$folder/test/reports/results.html"
