#!/bin/bash
source common.sh

./setup-activiti

docker run betsy-activiti sh betsy bpmn --use-installed-engine activiti "$*"

params=`echo "$*" | tr ' =' '_'`
folder=results/betsy-bpel-activiti-$params-`date +%s`
container=`docker ps -alq`

extractLogs "$container" "$folder"
open "$folder/test/reports/results.html"
