# This is a Dockerfile to create an image with betsy and the engine active-bpel installed.

# Version 1.0

FROM betsy

MAINTAINER Simon Harrer (simon.harrer@uni-bamberg.de)

# install active-bpel
RUN ./betsy engine active-bpel install
