# This is a Dockerfile to create an image with betsy and the engine ode installed.

# Version 1.0

FROM betsy

MAINTAINER Simon Harrer (simon.harrer@uni-bamberg.de)

# install ode
RUN ./betsy engine ode install
