# This is a Dockerfile to create an image with betsy and the engine activiti installed.

# Version 1.0

FROM betsy

MAINTAINER Simon Harrer (simon.harrer@uni-bamberg.de)

# install activiti
RUN ./betsy engine activiti install
